import type { CalendarEvent } from './types';

export const dailyEvents: CalendarEvent[] = [
  {
    id: 'morning-routine',
    time: '7:30am',
    title: 'Morning Routine',
    emoji: '🌅',
    category: 'sage',
    recurrence: 'daily',
  },
  {
    id: 'morning-skincare',
    time: '8:00am',
    title: 'Morning Skincare',
    emoji: '✨',
    category: 'flamingo',
    recurrence: 'daily',
  },
  {
    id: 'cat-morning-meds',
    time: '9:00am',
    title: 'Cat Morning Meds',
    emoji: '🐱',
    category: 'tomato',
    isNonNegotiable: true,
    doubleAlarm: true,
    recurrence: 'daily',
  },
  {
    id: 'breakfast',
    time: '9:15am',
    title: 'Breakfast',
    emoji: '🍳',
    category: 'banana',
    recurrence: 'daily',
  },
  {
    id: 'am-cat-playtime',
    time: '9:30am',
    title: 'AM Cat Playtime',
    emoji: '🐱',
    category: 'tomato',
    recurrence: 'daily',
  },
  {
    id: 'cat-midday-snack',
    time: '12:30pm',
    title: 'Cat Midday Snack + Play',
    emoji: '🐱',
    category: 'tomato',
    recurrence: 'daily',
  },
  {
    id: 'eaten-today',
    time: '1:00pm',
    title: 'Eaten today?',
    emoji: '🍽️',
    category: 'banana',
    recurrence: 'daily',
    note: 'You don\'t have to cook. You just have to eat something.',
  },
  {
    id: 'dinner',
    time: '6:30pm',
    title: 'Dinner',
    emoji: '🍽️',
    category: 'banana',
    recurrence: 'daily',
  },
  {
    id: 'pm-cat-playtime',
    time: '7:30pm',
    title: 'PM Cat Playtime',
    emoji: '🐱',
    category: 'tomato',
    recurrence: 'daily',
  },
  {
    id: 'evening-routine',
    time: '9:00pm',
    title: 'Evening Routine',
    emoji: '🌙',
    category: 'sage',
    recurrence: 'daily',
  },
  {
    id: 'cat-evening-meds',
    time: '9:00pm',
    title: 'Cat Evening Meds + Dinner + Litter',
    emoji: '🐱',
    category: 'tomato',
    isNonNegotiable: true,
    doubleAlarm: true,
    recurrence: 'daily',
  },
  {
    id: 'bedtime-meds',
    time: '9:30pm',
    title: 'Your Bedtime Meds',
    emoji: '💊',
    category: 'tomato',
    isNonNegotiable: true,
    doubleAlarm: true,
    recurrence: 'daily',
    note: 'On a hard day: just those two. Done.',
  },
  {
    id: 'night-skincare',
    time: '9:45pm',
    title: 'Night Skincare',
    emoji: '✨',
    category: 'flamingo',
    recurrence: 'daily',
  },
  {
    id: 'lights-out',
    time: '11:00pm',
    title: 'Lights Out by 11pm',
    emoji: '💤',
    category: 'graphite',
    recurrence: 'daily',
  },
];

export const everyTwoDaysEvents: CalendarEvent[] = [
  {
    id: 'shower-checkin',
    title: 'Shower check-in',
    emoji: '🚿',
    category: 'flamingo',
    recurrence: 'interval',
    intervalDays: 2,
    note: 'Non-negotiable on whether, flexible on which.',
  },
];

export const weeklyEvents: CalendarEvent[] = [
  {
    id: 'room-reset-tuesday',
    time: '5:30pm',
    title: 'Room Reset',
    emoji: '🧹',
    category: 'graphite',
    recurrence: 'weekly',
    days: ['tuesday', 'saturday'],
  },
  {
    id: 'deep-focus-wednesday',
    time: '10:00am',
    title: 'Deep Focus: Project Session',
    emoji: '🔵',
    category: 'blueberry',
    recurrence: 'weekly',
    days: ['wednesday'],
    note: 'Protected time. No calls, no notifications, no obligations.',
  },
  {
    id: 'outside-time-thursday',
    time: '2:00pm',
    title: 'Outside Time',
    emoji: '🌿',
    category: 'basil',
    recurrence: 'weekly',
    days: ['thursday'],
    note: 'body + spirituality + feedstock in one block. Don\'t plan it to death. Just go outside.',
  },
  {
    id: 'cat-brushing-mwf',
    time: '7:00pm',
    title: 'Cat Brushing',
    emoji: '🐱',
    category: 'tomato',
    recurrence: 'weekly',
    days: ['monday', 'wednesday', 'friday'],
  },
  {
    id: 'applied-buddhism',
    time: '9:00am',
    title: 'Applied Buddhism & Meditation (Optional)',
    emoji: '🛕',
    category: 'peacock',
    recurrence: 'weekly',
    days: ['saturday'],
    isOptional: true,
  },
  {
    id: 'deep-focus-saturday',
    time: '10:00am',
    title: 'Deep Focus: Creative Session',
    emoji: '🔵',
    category: 'blueberry',
    recurrence: 'weekly',
    days: ['saturday'],
    note: 'Protected time. No calls, no notifications, no obligations.',
  },
  {
    id: 'laundry',
    time: '2:00pm',
    title: 'Laundry',
    emoji: '🧳',
    category: 'graphite',
    recurrence: 'weekly',
    days: ['saturday'],
  },
  {
    id: 'cat-full-groom',
    time: '10:00am',
    title: 'Cat Full Groom',
    emoji: '🐱',
    category: 'tomato',
    recurrence: 'weekly',
    days: ['sunday'],
  },
  {
    id: 'sunday-self-care',
    time: '11:00am',
    title: 'Sunday Self-Care Block',
    emoji: '🌸',
    category: 'flamingo',
    recurrence: 'weekly',
    days: ['sunday'],
  },
  {
    id: 'call-mom',
    time: '4:00pm',
    title: 'Call Mom',
    emoji: '📞',
    category: 'flamingo',
    recurrence: 'weekly',
    days: ['sunday'],
  },
  {
    id: 'checkin-sister',
    time: '5:00pm',
    title: 'Check in with Sister',
    emoji: '📱',
    category: 'flamingo',
    recurrence: 'weekly',
    days: ['sunday'],
  },
  {
    id: 'instacart',
    time: '6:30pm',
    title: 'Instacart Order',
    emoji: '🛒',
    category: 'banana',
    recurrence: 'weekly',
    days: ['sunday'],
  },
  {
    id: 'transfer-notes',
    time: '6:45pm',
    title: 'Transfer Notes → Notecards',
    emoji: '📱',
    category: 'graphite',
    recurrence: 'weekly',
    days: ['sunday'],
  },
  {
    id: 'weekly-setup',
    time: '7:00pm',
    title: 'Weekly Setup',
    emoji: '🟣',
    category: 'grape',
    recurrence: 'weekly',
    days: ['sunday'],
  },
];

export const biweeklyEvents: CalendarEvent[] = [
  {
    id: 'checkin-annie',
    title: 'Check in with Annie',
    category: 'flamingo',
    recurrence: 'biweekly',
    startDate: '2026-04-12',
  },
  {
    id: 'creative-adventure',
    title: 'Creative Adventure',
    category: 'grape',
    recurrence: 'biweekly',
    startDate: '2026-04-18',
  },
  {
    id: 'trader-joes-check',
    title: "Trader Joe's Frozen Meal Check",
    category: 'banana',
    recurrence: 'biweekly',
    startDate: '2026-04-14',
  },
];

export const monthlyEvents: CalendarEvent[] = [
  {
    id: 'monthly-reset',
    time: '9:00am',
    title: 'Monthly Reset + Budget Hour',
    emoji: '🟣',
    category: 'grape',
    recurrence: 'monthly',
    monthlyRule: { type: 'nth-weekday', weekday: 'sunday', nth: 1 },
  },
  {
    id: 'cat-supply-check',
    time: '1:00pm',
    title: 'Cat Supply Check',
    emoji: '🐱',
    category: 'tomato',
    recurrence: 'monthly',
    monthlyRule: { type: 'nth-weekday', weekday: 'sunday', nth: 1 },
  },
  {
    id: 'pay-credit-card',
    title: 'Pay Credit Card Bill',
    emoji: '💳',
    category: 'banana',
    recurrence: 'monthly',
    monthlyRule: { type: 'day-of-month', day: 2 },
  },
  {
    id: 'pay-mom',
    title: 'Pay Mom',
    emoji: '💛',
    category: 'banana',
    recurrence: 'monthly',
    monthlyRule: { type: 'day-of-month', day: 15 },
  },
  {
    id: 'pay-partner-rent',
    title: 'Pay Partner Rent',
    emoji: '🏠',
    category: 'banana',
    recurrence: 'monthly',
    monthlyRule: { type: 'last-day' },
  },
  {
    id: 'reorder-cat-meds',
    title: 'Reorder Cat Medication',
    emoji: '🐱',
    category: 'tomato',
    recurrence: 'monthly',
  },
  {
    id: 'vet-food-check',
    title: 'Vet Food Check',
    emoji: '🐱',
    category: 'tomato',
    recurrence: 'interval',
    intervalDays: 11,
  },
  {
    id: 'rotate-cat-toys',
    title: 'Rotate Cat Toys',
    emoji: '🐱',
    category: 'tomato',
    recurrence: 'monthly',
    monthlyRule: { type: 'nth-weekday', weekday: 'friday', nth: 1 },
  },
  {
    id: 'replace-scratchers',
    title: 'Check + Replace Scratchers',
    emoji: '🐱',
    category: 'tomato',
    recurrence: 'interval',
    intervalDays: 60,
  },
];

export const aprilOneTimeEvents: CalendarEvent[] = [
  {
    id: 'apr1-family-meeting',
    date: '2026-04-01',
    time: '6:00pm',
    title: 'Family Meeting 6–7pm',
    category: 'flamingo',
    recurrence: 'one-time',
    isUrgent: true,
  },
  {
    id: 'apr1-contact-therapists',
    date: '2026-04-01',
    title: 'Contact Therapists',
    category: 'flamingo',
    recurrence: 'one-time',
    isUrgent: true,
    note: 'URGENT — do today',
  },
  {
    id: 'apr2-capital-one',
    date: '2026-04-02',
    title: 'Capital One double charge check',
    category: 'banana',
    recurrence: 'one-time',
    isUrgent: true,
  },
  {
    id: 'apr2-schedule-psychiatry',
    date: '2026-04-02',
    title: 'Schedule Psychiatry',
    category: 'flamingo',
    recurrence: 'one-time',
    isUrgent: true,
  },
  {
    id: 'apr2-maisie-insurance',
    date: '2026-04-02',
    title: 'Add Maisie to pet insurance',
    category: 'tomato',
    recurrence: 'one-time',
    isUrgent: true,
  },
  {
    id: 'apr2-reply-mom',
    date: '2026-04-02',
    title: 'REPLY to mom Chicago flights (EOD)',
    category: 'flamingo',
    recurrence: 'one-time',
    isUrgent: true,
  },
  {
    id: 'apr3-birthday-email',
    date: '2026-04-03',
    title: "Send Birthday Email to Mom",
    category: 'flamingo',
    recurrence: 'one-time',
  },
  {
    id: 'apr4-hair-detangle',
    date: '2026-04-04',
    time: '11:00am',
    title: 'Hair Detangle Session 11am–1pm',
    category: 'flamingo',
    recurrence: 'one-time',
  },
  {
    id: 'apr5-financial-review',
    date: '2026-04-05',
    title: 'Financial Review',
    category: 'banana',
    recurrence: 'one-time',
  },
  {
    id: 'apr5-gap-gift-cards',
    date: '2026-04-05',
    title: 'Gap Gift Cards',
    category: 'banana',
    recurrence: 'one-time',
  },
  {
    id: 'apr8-usps',
    date: '2026-04-08',
    title: 'USPS Identity Verification Deadline',
    category: 'tangerine',
    recurrence: 'one-time',
    isUrgent: true,
  },
  {
    id: 'apr10-taxes',
    date: '2026-04-10',
    title: 'FILE TAXES (deadline Apr 15)',
    category: 'tangerine',
    recurrence: 'one-time',
    isUrgent: true,
  },
  {
    id: 'apr13-sdge',
    date: '2026-04-13',
    title: 'SDG&E Bill $127.09',
    category: 'banana',
    recurrence: 'one-time',
    isUrgent: true,
  },
  {
    id: 'apr15-tax-day',
    date: '2026-04-15',
    title: 'TAX DAY',
    category: 'tangerine',
    recurrence: 'one-time',
    isUrgent: true,
  },
  {
    id: 'apr15-pay-mom',
    date: '2026-04-15',
    title: 'Pay Mom',
    category: 'banana',
    recurrence: 'one-time',
  },
  {
    id: 'apr19-glen-ivy',
    date: '2026-04-19',
    title: 'Glen Ivy with Mom (book now)',
    category: 'flamingo',
    recurrence: 'one-time',
    isUrgent: true,
  },
  {
    id: 'apr24-contract-checkin',
    date: '2026-04-24',
    title: '4 Weeks to Contract End Check-In',
    category: 'blueberry',
    recurrence: 'one-time',
  },
  {
    id: 'apr25-animal-photos',
    date: '2026-04-25',
    time: '8:00am',
    title: 'Send Animal Photos to Amber',
    category: 'flamingo',
    recurrence: 'one-time',
  },
  {
    id: 'apr25-animal-comm',
    date: '2026-04-25',
    time: '10:00am',
    title: 'Animal Communication Session 10am–11am',
    category: 'flamingo',
    recurrence: 'one-time',
  },
  {
    id: 'apr25-birthday',
    date: '2026-04-25',
    title: 'YOUR BIRTHDAY 🎂',
    category: 'flamingo',
    recurrence: 'one-time',
  },
  {
    id: 'apr25-safari-park',
    date: '2026-04-25',
    title: 'Safari Park + Dinner',
    category: 'flamingo',
    recurrence: 'one-time',
  },
  {
    id: 'apr26-dar-birthday',
    date: '2026-04-26',
    title: "Plan Dar's Birthday (May 16)",
    category: 'flamingo',
    recurrence: 'one-time',
  },
  {
    id: 'apr26-mothers-day',
    date: '2026-04-26',
    title: "Plan Mother's Day (May 10)",
    category: 'flamingo',
    recurrence: 'one-time',
  },
];

export const allEvents = [
  ...dailyEvents,
  ...everyTwoDaysEvents,
  ...weeklyEvents,
  ...biweeklyEvents,
  ...monthlyEvents,
  ...aprilOneTimeEvents,
];

export const monthlyBudgetSteps = [
  { order: 1, title: 'Review last month', description: 'Check all accounts, note any surprises' },
  { order: 2, title: 'Subscription audit', description: 'Cancel anything not used in 30 days' },
  { order: 3, title: 'Upcoming obligations', description: 'Note fixed bills for next 30 days' },
  { order: 4, title: 'Set monthly intention', description: 'One financial goal for this month' },
  { order: 5, title: 'Buffer check', description: 'Is there a 2-week buffer? If not, pause discretionary spending' },
];
